# Generated by Django 4.2 on 2023-04-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_addiproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproject',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AddiProject',
        ),
    ]
