# Generated by Django 4.2 on 2023-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_newproject_created_by_delete_addiproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddiProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('endDate', models.DateField()),
                ('startDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
