# Generated by Django 4.2 on 2023-04-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_addiproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddiProject',
        ),
    ]
